# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d177d28b96fb45fc7194c4ec1368b7415260b893295affdd181825c76ad7e741635e39fc20cdfc9ad28652da98fb93ea24b627bad8e7e4dd0c1f8fe146b68364

test:
  secret_key_base: 38cca3df64c2021dbd5cc766a8fd88d0a06cae0f1674e3a9fa0058cbacc82b9ed7f7f8c466b3dec76206e1615279ad5270a857e4aef05d0677895d90e9ee713b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
